name: Build and Publish APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create directories for google-services.json and Maps API Key
        run: |
          mkdir -p ./app/src/release/
          mkdir -p ./app/src/main/res/values/

      - name: Decode and create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > ./app/src/release/google-services.json

      - name: Create Maps API Key XML
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>' > ./app/src/main/res/values/maps_api.xml
          echo '<resources>' >> ./app/src/main/res/values/maps_api.xml
          echo '    <string name="maps_api_key">'$MAPS_API_KEY'</string>' >> ./app/src/main/res/values/maps_api.xml
          echo '</resources>' >> ./app/src/main/res/values/maps_api.xml

      - name: Create APK output directory
        run: mkdir -p ./app/build/outputs/apk/release/

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: List output directory
        run: ls -R ./app/build/outputs/

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
