name: Firebase Emulator Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the version compatible with your project

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Start Firebase Emulators
        run: firebase emulators:start --only firestore,functions --project dummy-project-id &
      - name: Run tests
        run: npm test  # Replace this with your actual test command
